# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  zookeeper:
    image: hyperledger/fabric-zookeeper
    restart: always

  kafka1:
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    ports:
      - '9092'
    depends_on:
      - zookeeper

  orderer:
    image: hyperledger/fabric-orderer
    restart: always
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_QUEUESIZE=1000
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - ORDERER_KAFKA_BROKERS=[kafka1:9092]
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
    ports:
      - 7050:7050
    command: orderer
    volumes:
      - /etc/hyperledger/msp:/etc/hyperledger/msp
    depends_on:
      - zookeeper
      - kafka1
