# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

    orderer0:
        extends:
            file: docker-compose-orderer-base.yml
            service: ordererBase
        environment:
            - CONFIGTX_ORDERER_ORDERERTYPE=solo
